urls:
    -   # xiu zheng si wan nian
        url: http://www.biqudao.com/bqge7946
        per: 1d
        count: 10
    -   #
        url: http://www.biqudao.com/bqge11388
        per: 1d
        count: 5
    -
        url: http://www.biqudao.com/bqge1081
        per: 1d
        count: 5

