urls:
    -   name: forty-thousand-years
        url: http://www.biqudao.com/bqge7946
        per: 1d
        count: 12

    -   name: into-cultivation
        url: http://www.biqudao.com/bqge11388
        per: 1d
        count: 5

    -   name: super-scholar
        url: http://www.biqudao.com/bqge1081
        per: 1d
        count: 5

